services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      - KUBECONFIG=/root/.kube/config
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      - /home/tsid_user03_tsmc_hackathon_cloud/.kube/config:/root/.kube/config:ro  # Mount local kubeconfig file
      - /home/tsid_user03_tsmc_hackathon_cloud/.config/gcloud:/root/.config/gcloud  # Mount local gcloud config
