services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      - KUBECONFIG=/root/.kube/config
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      - ~/.kube:/root/.kube:ro  # Mount local kubeconfig file
      - ~/.config/gcloud:/root/.config/gcloud  # Mount local gcloud config
