apiVersion: batch/v1
kind: Job
metadata:
  name: python3-job
  namespace: default
spec:
  backoffLimit: 1 
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: python3-container
        image: us-central1-docker.pkg.dev/tsmccareerhack2025-tsid-grp1/tsmccareerhack2025-tsid-grp1-repository/python3:latest
        command: ["python3", "placeholder"]
        volumeMounts:
        - name: config-volume
          mountPath: "/mnt/config"
      volumes:
      - name: config-volume
        configMap:
          name: placeholder-config 